from initdb import PvPAggregate, AccountMedals

statDict = { "kd"           :(PvPAggregate, "killsDeathsRatio", "Kill/Death Ratio")
            ,"kda"          :(PvPAggregate, "killsDeathsAssists", "Kill/Assists/Death Ratio")
            ,"wl"           :(PvPAggregate, "winLossRatio", "Win/Loss Ratio")
            ,"bgs"          :(PvPAggregate, "bestSingleGameScore", "Best Single Game Score")
            ,"lks"          :(PvPAggregate, "longestKillSpree", "Longest Kill Spree")
            ,"suicides"     :(PvPAggregate, "suicides", "Total Number of Suicides")
            ,"spg"          :(PvPAggregate, "suicidespg", "Suicides per Game")
            ,"mk"           :(PvPAggregate, "bestSingleGameKills", "Best Single Game Kills")
            ,"kills"        :(PvPAggregate, "kills", "Total Number of Kills")
            ,"kpg"          :(PvPAggregate, "killspg", "Kills per Game")
            ,"deaths"       :(PvPAggregate, "deaths", "Total Number of Deaths")
            ,"dpg"          :(PvPAggregate, "deathspg", "Deaths per Game")
            ,"assists"      :(PvPAggregate, "assists", "Total Number of Assists")
            ,"apg"          :(PvPAggregate, "assistspg", "Assists Per Game")
            ,"cr"           :(PvPAggregate, "combatRating", "Combat Rating")
            ,"pkills"       :(PvPAggregate, "precisionKills", "Total Number of Precision Kills")
            ,"score"        :(PvPAggregate, "score", "Total score")
            ,"scpg"         :(PvPAggregate, "scorepg", "Score per Game")
            ,"crucibletime" :(PvPAggregate, "secondsPlayed", "Total Seconds in the Crucible")
            ,"akills"       :(PvPAggregate, "abilityKills", "Total Number of Ability Kills")
            ,"akpg"         :(PvPAggregate, "abilityKillspg", "Ability Kills per Game")
            ,"games"        :(PvPAggregate, "activitiesEntered", "Total Number of Activities Entered")
            ,"wins"         :(PvPAggregate, "activitiesWon", "Total Number of Activities Won")
            ,"lsl"          :(PvPAggregate, "longestSingleLife", "Longest Single Life")
            }

medalDict = { "activities"        :(AccountMedals, "activitiesEntered", "Activities Entered")
             ,"totalmedals"       :(AccountMedals, "allMedalsEarned", "Total Number of Medals")
             ,"totalscore"        :(AccountMedals, "allMedalsScore", "Total Medal Score")
             ,"stormbringer"      :(AccountMedals, "medalsAbilityArcLightningKillMulti", "Storm Bringer")
             ,"wayofthegun"       :(AccountMedals, "medalsAbilityGhostGunKillMulti", "Way of the Gun")
             ,"cryhavoc"          :(AccountMedals, "medalsAbilityHavocKillMulti", "Cry Havoc")
             ,"spacemagic"        :(AccountMedals, "medalsAbilityNovaBombKillMulti", "Space Magic")
             ,"scorchedearth"     :(AccountMedals, "medalsAbilityRadianceGrenadeKillMulti", "Scorched Earth")
             ,"gutted"            :(AccountMedals, "medalsAbilityShadowStrikeKillMulti", "Gutted")
             ,"hammerandtongs"    :(AccountMedals, "medalsAbilityThermalHammerKillMulti", "Hammer and Tongs")
             ,"wildhunt"          :(AccountMedals, "medalsAbilityVoidBowKillMulti", "Wild Hunt")
             ,"blastshield"       :(AccountMedals, "medalsAbilityWardDeflect", "Blast Shield")
             ,"objectivelycorrect":(AccountMedals, "medalsActivityCompleteControlMostCaptures", "Objectively Correct")
             ,"thecycle"          :(AccountMedals, "medalsActivityCompleteCycle", "The Cycle")
             ,"unbroken"          :(AccountMedals, "medalsActivityCompleteDeathless", "Mark of the Unbroken")
             ,"onthebrightside"   :(AccountMedals, "medalsActivityCompleteHighestScoreLosing", "On the Bright Side...")
             ,"thebestaround"     :(AccountMedals, "medalsActivityCompleteHighestScoreWinning", "The Best... Around")
             ,"lonewolf"          :(AccountMedals, "medalsActivityCompleteLonewolf", "Lone Wolf")
             ,"saboteur"          :(AccountMedals, "medalsActivityCompleteSalvageMostCancels", "Saboteur")
             ,"shutout"           :(AccountMedals, "medalsActivityCompleteSalvageShutout", "Shutout")
             ,"perfectrunner"     :(AccountMedals, "medalsActivityCompleteSingularityPerfectRunner", "Perfect Runner")
             ,"decisivevictory"   :(AccountMedals, "medalsActivityCompleteVictoryBlowout", "Decisive Victory")
             ,"victory"           :(AccountMedals, "medalsActivityCompleteVictory", "Victory")
             ,"trialbyfire"       :(AccountMedals, "medalsActivityCompleteVictoryElimination", "Trial by Fire")
             ,"bulletproof"       :(AccountMedals, "medalsActivityCompleteVictoryEliminationPerfect", "Bulletproof")
             ,"annihilation"      :(AccountMedals, "medalsActivityCompleteVictoryEliminationShutout", "Annihilation")
             ,"clutch"            :(AccountMedals, "medalsActivityCompleteVictoryExtraLastSecond", "Clutch")
             ,"comeback"          :(AccountMedals, "medalsActivityCompleteVictoryLastSecond", "Comeback")
             ,"nomercy"           :(AccountMedals, "medalsActivityCompleteVictoryMercy", "No Mercy")
             ,"sumofalltears"     :(AccountMedals, "medalsActivityCompleteVictoryRumbleBlowout", "Sum of all Tears")
             ,"aloneatthetop"     :(AccountMedals, "medalsActivityCompleteVictoryRumble", "Alone at the Top")
             ,"wontbebeat"        :(AccountMedals, "medalsActivityCompleteVictoryRumbleLastSecond", "Won't be Beat")
             ,"heartbreaker"      :(AccountMedals, "medalsActivityCompleteVictoryRumbleSuddenDeath", "Heartbreaker")
             ,"zerohour"          :(AccountMedals, "medalsActivityCompleteVictorySuddenDeath", "Zero Hour")
             ,"avenger"           :(AccountMedals, "medalsAvenger", "Avenger")
             ,"medic"             :(AccountMedals, "medalsBuddyResurrectionMulti", "Medic!")
             ,"angeloflight"      :(AccountMedals, "medalsBuddyResurrectionSpree", "Angel of Light")
             ,"narrowescape"      :(AccountMedals, "medalsCloseCallTalent", "Narrow Escape")
             ,"backinaction"      :(AccountMedals, "medalsComebackKill", "Back in Action")
             ,"domination"        :(AccountMedals, "medalsDominationKill", "Domination")
             ,"hattrick"          :(AccountMedals, "medalsDominionZoneCapturedSpree", "Hat Trick")
             ,"defender"          :(AccountMedals, "medalsDominionZoneDefenseKillSpree", "Defender")
             ,"atanycost"         :(AccountMedals, "medalsDominionZoneOffenseKillSpree", "At any Cost")
             ,"neversaydie"       :(AccountMedals, "medalsEliminationLastStandKill", "Never Say Die")
             ,"fromthebrink"      :(AccountMedals, "medalsEliminationLastStandRevive", "From the Brink")
             ,"ace"               :(AccountMedals, "medalsEliminationWipeQuick", "Ace")
             ,"wreckingball"      :(AccountMedals, "medalsEliminationWipeSolo", "Wrecking Ball")
             ,"firstblood"        :(AccountMedals, "medalsFirstBlood", "First Blood")
             ,"uprising"          :(AccountMedals, "medalsFirstPlaceKillSpree", "Uprising")
             ,"getitoff"          :(AccountMedals, "medalsGrenadeKillStick", "Get it Off!")
             ,"hazardpay"         :(AccountMedals, "medalsHazardKill", "Hazard Pay")
             ,"iseeyou"           :(AccountMedals, "medalsHunterKillInvisible", "I See You")
             ,"unsunghero"        :(AccountMedals, "medalsKillAssistSpree", "Unsung Hero")
             ,"enemyofmyenemy"    :(AccountMedals, "medalsKillAssistSpreeFfa", "Enemy of my Enemy")
             ,"bullseye"          :(AccountMedals, "medalsKillHeadshot", "Bullseye")
             ,"enforcer"          :(AccountMedals, "medalsKilljoy", "Enforcer")
             ,"endoftheline"      :(AccountMedals, "medalsKilljoyMega", "End of the Line")
             ,"doubledown"        :(AccountMedals, "medalsKillMulti2", "Double Down")
             ,"tripledown"        :(AccountMedals, "medalsKillMulti3", "Triple Down")
             ,"breaker"           :(AccountMedals, "medalsKillMulti4", "Breaker")
             ,"slayer"            :(AccountMedals, "medalsKillMulti5", "Slayer")
             ,"reaper"            :(AccountMedals, "medalsKillMulti6", "Reaper")
             ,"seventhcolumn"     :(AccountMedals, "medalsKillMulti7", "Seventh Column")
             ,"postmortem"        :(AccountMedals, "medalsKillPostmortem", "Postmortem")
             ,"merciless"         :(AccountMedals, "medalsKillSpree1", "Merciless")
             ,"relentless"        :(AccountMedals, "medalsKillSpree2", "Relentless")
             ,"reignofterror"     :(AccountMedals, "medalsKillSpree3", "Reign of Terror")
             ,"weranoutofmedals"  :(AccountMedals, "medalsKillSpreeAbsurd", "We Ran Out of Medals")
             ,"phantom"           :(AccountMedals, "medalsKillSpreeNoDamage", "Phantom")
             ,"stickaround"       :(AccountMedals, "medalsMeleeKillHunterThrowingKnifeHeadshot", "Stick Around")
             ,"payback"           :(AccountMedals, "medalsPaybackKill", "Payback")
             ,"andstaydown"       :(AccountMedals, "medalsRadianceShutdown", "...And Stay Down!")
             ,"overwatch"         :(AccountMedals, "medalsRescue", "Overwatch")
             ,"disruption"        :(AccountMedals, "medalsSalvageProbeCanceled", "Disruption")
             ,"salvagecrew"       :(AccountMedals, "medalsSalvageProbeCompleteSpree", "Salvage Crew")
             ,"improbeable"       :(AccountMedals, "medalsSalvageProbeDefenseKill", "Im-probe-able")
             ,"cleansweep"        :(AccountMedals, "medalsSalvageProbeOffenseKillMulti", "Clean Sweep")
             ,"relichunter"       :(AccountMedals, "medalsSalvageZoneCapturedSpree", "Relic Hunter")
             ,"unstoppableforce"  :(AccountMedals, "medalsSingularityFlagCaptureMulti", "Unstoppable Force")
             ,"denied"            :(AccountMedals, "medalsSingularityFlagHolderKilledClose", "Denied")
             ,"immovableobject"   :(AccountMedals, "medalsSingularityFlagHolderKilledMulti", "Immovable Object")
             ,"clearapath"        :(AccountMedals, "medalsSingularityRunnerDefenseMulti", "Clear a Path")
             ,"afistfulofcrests"  :(AccountMedals, "medalsSupremacy", "A Fistful of Crests...")
             ,"forafewcrestsmore" :(AccountMedals, "medalsSupremacyConfirmStreakLarge", "And For a Few Crests More")
             ,"honorguard"        :(AccountMedals, "medalsSupremacyDenyMulti", "Honor Guard")
             ,"mineallmine"       :(AccountMedals, "medalsSupremacyMostConfirms", "Mine! All Mine!")
             ,"handsoff"          :(AccountMedals, "medalsSupremacyMostDenies", "Hands Off")
             ,"illdoitmyself"     :(AccountMedals, "medalsSupremacyMostSelfConfirms", "I'll Do It Myself")
             ,"pickupthepieces"   :(AccountMedals, "medalsSupremacyMulti", "Pick Up the Pieces")
             ,"nevergonnagetit"   :(AccountMedals, "medalsSupremacyNeverCollected", "Never Gonna Get It")
             ,"nevermindfoundit"  :(AccountMedals, "medalsSupremacySelfDeny", "Never Mind, Found It")
             ,"lockdown"          :(AccountMedals, "medalsTeamDominationHold1m", "Lockdown")
             ,"strengthofthewolf" :(AccountMedals, "medalsTeamKillSpree", "Strength of the Wolf")
             ,"unknown"           :(AccountMedals, "medalsUnknown", "Unknown")
             ,"gunner"            :(AccountMedals, "medalsVehicleFotcTurretKillSpree", "Gunner")
             ,"bulldozer"         :(AccountMedals, "medalsVehicleInterceptorKillSplatter", "Bulldozer")
             ,"chariotoffire"     :(AccountMedals, "medalsVehicleInterceptorKillSpree", "Chariot of Fire")
             ,"skewered"          :(AccountMedals, "medalsVehiclePikeKillSplatter", "Skewered")
             ,"fallenangel"       :(AccountMedals, "medalsVehiclePikeKillSpree", "Fallen Angel")
             ,"neverspeakofthis"  :(AccountMedals, "medalsVehicleSparrowKillSplatter", "Never Speak of This Again")
             ,"automatic"         :(AccountMedals, "medalsWeaponAutoRifleKillSpree", "Automatic")
             ,"masterblaster"     :(AccountMedals, "medalsWeaponFusionRifleKillSpree", "Master Blaster")
             ,"deadmanshand"      :(AccountMedals, "medalsWeaponHandCannonHeadshotSpree", "Dead Man's Hand")
             ,"machinelord"       :(AccountMedals, "medalsWeaponMachineGunKillSpree", "Machine Lord")
             ,"fingeronthepulse"  :(AccountMedals, "medalsWeaponPulseRifleKillSpree", "Finger on the Pulse")
             ,"splashdamage"      :(AccountMedals, "medalsWeaponRocketLauncherKillSpree", "Splash Damage")
             ,"scoutshonor"       :(AccountMedals, "medalsWeaponScoutRifleKillSpree", "Scout's Honor")
             ,"buckshotbruiser"   :(AccountMedals, "medalsWeaponShotgunKillSpree", "Buckshot Bruiser")
             ,"sidekick"          :(AccountMedals, "medalsWeaponSidearmKillSpree", "Sidekick")
             ,"marksman"          :(AccountMedals, "medalsWeaponSniperRifleHeadshotSpree", "Marksman")
             ,"swordatagunfight"  :(AccountMedals, "medalsWeaponSwordKillSpree", "Sword at a Gun Fight")
             ,"nailinthecoffin"   :(AccountMedals, "medalsWinningScore", "Nail in the Coffin")
             ,"bline"             :(AccountMedals, "medalsZoneCapturedBInitial", "B-Line")
             }


